#define _CRT_SECURE_NO_WARNINGS
#include <math.h>
#include <stdio.h>
#include <limits.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include "tests.h"

const char VALID_OPERATORS[] = {'+', '-', '*', '/'};
const int VALID_SOLUTIONS = 3188;

double apply_operator(double number1, double number2, char operator) {
	if (operator == '+') {
		return number1 + number2;
	}
	else if (operator == '-') {
		return number1 - number2;
	}
	else if (operator == '*') {
		return number1 * number2;
	}

	return number1 / number2;
}

int is_valid_operator(char op) {
	return op == '+' || op == '-' || op == '*' || op == '/';
}

int verify_solution(int* digits, char* operators, int to_print) {
	double result = digits[0], old_result;
	for (int i = 0; i < 3; ++i) {
		old_result = result;
		result = apply_operator(result, (double)digits[i + 1], operators[i]);
		if (to_print) {
			printf("%lf %c %d = %lf\n", old_result, operators[i], digits[i + 1], result);
		}
	}

	double diff = result - 24;
	return diff >= 0 && diff < 0.00001;
}

void generate_combinations(int k, int* line, int *curr_numbers, char *curr_operators, int** numbers, char** operators) {
	if (k == 7) {
		if (verify_solution(curr_numbers, curr_operators, 0) && *line < 3188) {
			for (int i = 0; i < 4; ++i) {
				numbers[*line][i] = curr_numbers[i];
			}
			for (int i = 0; i < 3; ++i) {
				operators[*line][i] = curr_operators[i];
			}
			++(*line);
		}
		return;
	}

	if (k < 4) {
		for (int i = 1; i <= 9; ++i) {
			curr_numbers[k] = i;
			generate_combinations(k + 1, line, curr_numbers, curr_operators, numbers, operators);
		}
	}
	else {
		for (int i = 0; i < 4; ++i) {
			curr_operators[k - 4] = VALID_OPERATORS[i];
			generate_combinations(k + 1, line, curr_numbers, curr_operators, numbers, operators);
		}
	}
}

void generateAllCombinations(int** numbers, char** operators) {
	int line = 0, curr_numbers[4];
	char curr_operators[3];
	generate_combinations(0, &line, curr_numbers, curr_operators, numbers, operators);
}

void print_instructions() {
	printf("Welcome to the game of TwentyFour.\n");
	printf("Use each of the four numbers generated by the program exactly once, combining them somehow with the ");
	printf("basic mathematical operators(+, -, *, /) to yield the value of twenty-four.\n");
}

void print_numbers(int *numbers) {
	printf("The number to use are: %d, %d, %d, %d. ", numbers[0], numbers[1], numbers[2], numbers[3]);
	printf("Enter the three operators to be used, in order(+, -, *, /):");
}

void print_invalid_operators() {
	printf("The number of operators or the operators are invalid! Try again!\n");
}

void print_try_again() {
	printf("Would you like to play again? Enter N for no and any other characters for yes.");
}

void help_mode() {
	print_instructions();
}

void easy_mode() {
	print_instructions();
	int options[7][4] = { {1, 1, 4, 6},
		{1, 1, 3, 8},
		{1, 2, 2, 6},
		{1, 2, 3, 4},
		{1, 1, 3, 9},
		{4, 4, 4, 6},
		{1, 8, 8, 8}
	};

	int done = 0;
	char user_operators[64];

	while (!done) {
		int index = rand() % 7;
		print_numbers(options[index]);
		
		int valid = 0;
		while (!valid) {
			gets(user_operators);
			if (strlen(user_operators) == 3 && is_valid_operator(user_operators[0]) &&
				is_valid_operator(user_operators[1]) && is_valid_operator(user_operators[2])) {
				valid = 1;
			}
			else {
				print_invalid_operators();
			}
		}

		if (verify_solution(options[index], user_operators, 1)) {
			printf("Well done!\n");
		}
		else {
			printf("You lost! The result is not 24.\n");
		}

		valid = 0;
		char try_again[16];
		print_try_again();
		gets(try_again);
		if (try_again[0] == 'N') {
			done = 1;
		}
	}
}

void save_mode() {
	int** numbers = (int**)malloc(sizeof(int*) * VALID_SOLUTIONS);
	char** operators = (char**)malloc(sizeof(char*) * VALID_SOLUTIONS);

	for (int i = 0; i < VALID_SOLUTIONS; ++i) {
		numbers[i] = (int*)malloc(sizeof(int) * 4);
		operators[i] = (char*)malloc(sizeof(char) * 3);
	}

	generateAllCombinations(numbers, operators);

	FILE* f;
	f = fopen("solution.txt", "w");
	for (int i = 0; i < VALID_SOLUTIONS; ++i) {
		fprintf(f, "%d", numbers[i][0]);
		for (int j = 0; j < 3; ++j) {
			fprintf(f, "%c%d", operators[i][j], numbers[i][j + 1]);
		}
		fprintf(f, "\n");
	}

	fclose(f);

	for (int i = 0; i < VALID_SOLUTIONS; ++i) {
		free(numbers[i]);
		free(operators[i]);
	}
	free(numbers);
	free(operators);
}

void full_mode() {
	print_instructions();
	int **numbers = (int **) malloc(sizeof(int*) * VALID_SOLUTIONS);
	char** operators = (char**) malloc(sizeof(char*) * VALID_SOLUTIONS);

	for (int i = 0; i < VALID_SOLUTIONS; ++i) {
		numbers[i] = (int *) malloc(sizeof(int) * 4);
		operators[i] = (char*) malloc(sizeof(char) * 3);
	}

	generateAllCombinations(numbers, operators); 

	int done = 0;
	char user_operators[64];

	while (!done) {
		int index = rand() % VALID_SOLUTIONS;
		print_numbers(numbers[index]);

		int valid = 0;
		while (!valid) {
			gets(user_operators);
			if (strlen(user_operators) == 3 && is_valid_operator(user_operators[0]) &&
				is_valid_operator(user_operators[1]) && is_valid_operator(user_operators[2])) {
				valid = 1;
			}
			else {
				print_invalid_operators();
			}
		}

		if (verify_solution(numbers[index], user_operators, 1)) {
			printf("Well done!\n");
		}
		else {
			printf("You lost! The result is not 24.\n");
		}

		valid = 0;
		char try_again[16];
		print_try_again();
		gets(try_again);
		if (try_again[0] == 'N') {
			done = 1;
		}
	}

	for (int i = 0; i < VALID_SOLUTIONS; ++i) {
		free(numbers[i]);
		free(operators[i]);
	}
	free(numbers);
	free(operators);
}

int main(int argc, char **argv)
{
	if (argc != 1 && argc != 2) {
		printf("Invalid number of command line arguments!");
		exit(1);
	}

	srand(time(NULL));

	if (argc == 1) {
		full_mode();
	}
	else {
		if (!strcmp(argv[1], "-h")) {
			help_mode();
		}
		else if (!strcmp(argv[1], "-e")) {
			easy_mode();
		}
		else if (!strcmp(argv[1], "-s")) {
			save_mode();
		}
		else {
			printf("Invalid command line argument!");
			exit(1);
		}
	}

#if ENABLE_TESTS > 0
    run_tests(true);
#endif
    return 0;

}
